{
	"version": 1716002148,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background.png",
		"images/background_level.png",
		"images/layer_angle-sheet0.png",
		"images/character_control-sheet0.png",
		"images/character_control-sheet1.png",
		"images/box_control-sheet0.png",
		"images/box_control-sheet1.png",
		"images/button_right-sheet0.png",
		"images/button_right-sheet1.png",
		"images/button_left-sheet0.png",
		"images/button_left-sheet1.png",
		"images/sensor_collision-sheet0.png",
		"images/sensor_collision-sheet1.png",
		"images/sensor_collision-sheet2.png",
		"images/collision_mask_sensor-sheet0.png",
		"images/collision_mask_sensor-sheet1.png",
		"images/move_right.png",
		"images/move_left.png",
		"images/dirt-sheet0.png",
		"images/dirt_particles.png",
		"images/floor_vegetation_right.png",
		"images/feet_sensor-sheet0.png",
		"images/tilemap_floor.png",
		"images/tilemap_corners.png",
		"images/game_key-sheet0.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/door-sheet2.png",
		"images/padlock-sheet0.png",
		"images/padlock-sheet1.png",
		"images/padlock-sheet2.png",
		"images/overdoor-sheet0.png",
		"images/box-sheet0.png",
		"images/tilesguide.png",
		"images/spikes.png",
		"images/transition_mask-sheet0.png",
		"images/select_button-sheet0.png",
		"images/restart_button-sheet0.png",
		"images/dead_animations-sheet0.png",
		"images/dead_animations-sheet1.png",
		"images/ui_board-sheet0.png",
		"images/next_button-sheet0.png",
		"images/character-sheet0.png",
		"images/character-sheet1.png",
		"images/return_button-sheet0.png",
		"images/play_button-sheet0.png",
		"images/audio_button-sheet0.png",
		"images/audio_button-sheet1.png",
		"images/game_tittle-sheet0.png",
		"images/game_version-sheet0.png",
		"images/loading_bar.png",
		"images/loading_bar_overlay-sheet0.png",
		"images/loadin_text-sheet0.png",
		"images/loading_bar_background-sheet0.png",
		"images/previous_page-sheet0.png",
		"images/page_indicator_text.png",
		"images/level_window_indicator-sheet0.png",
		"images/level_window_indicator-sheet1.png",
		"images/level_numbers.png",
		"images/next_page-sheet0.png",
		"images/level_select_icon-sheet0.png",
		"images/background1-sheet0.png",
		"images/dust_effect-sheet0.png",
		"images/dust_effect-sheet1.png",
		"images/fire_base-sheet0.png",
		"images/fire-sheet0.png",
		"images/fire-sheet1.png",
		"images/over_doors-sheet0.png",
		"images/vegetation-sheet0.png",
		"images/floor_menus-sheet0.png",
		"images/back_secundary-sheet0.png",
		"images/web_decoration-sheet0.png",
		"images/game_tittle_complement-sheet0.png",
		"images/select_text-sheet0.png",
		"images/blood_particles.png",
		"images/ui_key-sheet0.png",
		"images/ui_key-sheet1.png",
		"images/next_text-sheet0.png",
		"images/confetti_effect-sheet0.png",
		"images/confetti_effect-sheet1.png",
		"images/restart_button2-sheet0.png",
		"images/u_points-sheet0.png",
		"images/level_indicator.png",
		"images/board_level-sheet0.png",
		"images/leveltext-sheet0.png",
		"images/torch_spawn-sheet0.png",
		"images/set_shadow-sheet0.png",
		"images/helpsquare-sheet0.png",
		"images/object_decoration_1-sheet0.png",
		"images/object_decoration_1-sheet1.png",
		"images/tutorial_1_trigger-sheet0.png",
		"images/tutorial_overlay-sheet0.png",
		"images/helping_hand-sheet0.png",
		"images/help_balloon-sheet0.png",
		"images/object_decoration_2-sheet0.png",
		"images/object_decoration_3-sheet0.png",
		"images/object_decoration_4-sheet0.png",
		"images/object_decoration_5-sheet0.png",
		"images/object_decoration_5-sheet1.png",
		"images/object_decoration_5-sheet2.png",
		"images/object_decoration_6-sheet0.png",
		"images/object_decoration_6-sheet1.png",
		"images/object_decoration_7-sheet0.png",
		"images/object_decoration_9-sheet0.png",
		"images/spike_check-sheet0.png",
		"images/sprite-sheet0.png",
		"images/stones.png",
		"images/floor_vegetation_left.png",
		"images/debug_background.png",
		"media/ui button sound 1.ogg",
		"media/walk 1.ogg",
		"media/walk 2.ogg",
		"media/fall collision.ogg",
		"media/box collision.ogg",
		"media/ui button sound 2.ogg",
		"media/key sound.ogg",
		"media/game win.ogg",
		"media/ui rotate button.ogg",
		"media/swipe sound.ogg",
		"media/death 1.ogg",
		"media/game over.ogg",
		"media/death 2.ogg",
		"media/dirt walk 1.ogg",
		"media/dirt walk 2.ogg",
		"media/dirt walk 3.ogg",
		"media/wood walk 1.ogg",
		"media/wood walk 2.ogg",
		"media/wood walk 3.ogg",
		"media/ambient sound.ogg",
		"media/main music 1.ogg",
		"media/main music 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png"
	]
}